# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocialNetwork' do

pod ‘IQKeyboardManager’
pod 'SVProgressHUD'
pod ‘AFNetworking’, ‘~> 3.0’
pod ‘JSONModel’

end
